# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Enable container name DNS for all docker networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "docker+" else "docker*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };
    
  # Containers
  virtualisation.oci-containers.containers."kasm" = {
    image = "lscr.io/linuxserver/kasm:latest";
    environment = {
      "DOCKER_HUB_PASSWORD" = "PASS";
      "DOCKER_HUB_USERNAME" = "USER";
      "DOCKER_MTU" = "1500";
      "KASM_PORT" = "443";
    };
    volumes = [
      "/dev/input:/dev/input:rw"
      "/run/udev/data:/run/udev/data:rw"
      "/services/kasmweb/data:/opt:rw"
      "/services/kasmweb/profiles:/profiles:rw"
    ];
    ports = [
      "3000:3000/tcp"
      "3030:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=kasm"
      "--network=kasmweb_default"
      "--privileged"
      "--security-opt=apparmor:rootlesskit"
    ];
  };
  systemd.services."docker-kasm" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "docker-network-kasmweb_default.service"
    ];
    requires = [
      "docker-network-kasmweb_default.service"
    ];
    partOf = [
      "docker-compose-kasmweb-root.target"
    ];
    wantedBy = [
      "docker-compose-kasmweb-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-kasmweb_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f kasmweb_default";
    };
    script = ''
      docker network inspect kasmweb_default || docker network create kasmweb_default
    '';
    partOf = [ "docker-compose-kasmweb-root.target" ];
    wantedBy = [ "docker-compose-kasmweb-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-kasmweb-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
