# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."nextcloud-aio-mastercontainer" = {
    image = "ghcr.io/nextcloud-releases/all-in-one:latest";
    environment = {
      "APACHE_ADDITIONAL_NETWORK" = "frontend_net";
      "APACHE_IP_BINDING" = "127.0.0.1";
      "APACHE_PORT" = "11000";
      "NEXTCLOUD_DATADIR" = "/services/nextcloud";
      "NEXTCLOUD_ENABLE_DRI_DEVICE" = "true";
      "NEXTCLOUD_STARTUP_APPS" = "deck twofactor_totp tasks calendar contacts notes";
      "NEXTCLOUD_UPLOAD_LIMIT" = "20G";
      "SKIP_DOMAIN_VALIDATION" = "false";
      "TALK_PORT" = "3478";
    };
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock:ro"
      "nextcloud_aio_mastercontainer:/mnt/docker-aio-config:rw"
    ];
    ports = [
      "80:80/tcp"
      "8080:8080/tcp"
      "8443:8443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nextcloud-aio-mastercontainer"
      "--network=nextcloud-aio"
    ];
  };
  systemd.services."docker-nextcloud-aio-mastercontainer" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-nextcloud-aio.service"
      "docker-volume-nextcloud_aio_mastercontainer.service"
    ];
    requires = [
      "docker-network-nextcloud-aio.service"
      "docker-volume-nextcloud_aio_mastercontainer.service"
    ];
    partOf = [
      "docker-compose-nextcloud-aio-root.target"
    ];
    wantedBy = [
      "docker-compose-nextcloud-aio-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-nextcloud-aio" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f nextcloud-aio";
    };
    script = ''
      docker network inspect nextcloud-aio || docker network create nextcloud-aio --opt=com.docker.network.driver.mtu=1440
    '';
    partOf = [ "docker-compose-nextcloud-aio-root.target" ];
    wantedBy = [ "docker-compose-nextcloud-aio-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-nextcloud_aio_mastercontainer" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect nextcloud_aio_mastercontainer || docker volume create nextcloud_aio_mastercontainer
    '';
    partOf = [ "docker-compose-nextcloud-aio-root.target" ];
    wantedBy = [ "docker-compose-nextcloud-aio-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-nextcloud-aio-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
